### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by brandonros** [developit/karmatic#13]
What would it take to be able to use this with Angular?

As it stands:

`beforeEach(module('foo.modules.components'));`

```
    ✗ encountered a declaration exception
	TypeError: module is not a function
	    at Suite.eval (webpack-internal:///337:11:16)
	    at eval (webpack-internal:///337:4:3)
	    at Object.eval (webpack-internal:///337:44:3)
	    at eval (webpack-internal:///337:45:30)
	    at Object.337 (./source/js/app/utils/session/foo.js:78:1)
	    at __webpack_require__ (./source/js/app/utils/session/foo.js:20:30)
	    at ./source/js/app/utils/session/foo.js:63:18
```

**Comment by developit** [comment]
Hi - you'd need to import angular. I'm not familiar with angular, but in general, you need to import things before you test them.

**Comment by dmitryevseev** [comment]
@brandonros if you already imported angular and it's still failing to find module, try to use a long reference for the mock module function: `angular.mock.module` instead of just `module`.

If it does not help also take a look at [this shim](https://github.com/gdi2290/angular-starter/issues/901)

**Comment by brandonros** [comment]
Can the karmatic creator update the README to show an example of where to put a project's webpack config? I'm currently still on Grunt and I need to switch, but, I'm not quite sure where to place the new webpack config.

Additionally, I kind of also don't know how to switch from bower to npm and then require all of my modules... Some of them weren't made to work with CommonJS/require()... so I am pretty sure I am screwed? Can somebody else confirm? (I didn't choose this tech stack, trying to help some people stuck on old tech out)

**Comment by thescientist13** [comment]
@brandonros 
In general, the common convention is generally to 
- put all configs (webpack, eslint, tsconfig, etc) in the root of the project
- a _src/_ directory for all app / source code (sometimes unit tests are co-located
- a _test/_ directory for all tests

Re: **Bower** -> **npm**, it should mostly be compatible since **npm** allows mapping to a "main" file from _package.json_ to an "entry point into said library (which **Bower** also had).

The tricky part comes in if you are working with **webpack** since nothing is global anymore, and a lot of pre ES2015+ libraries don't use `import` / `export` and so webpack can't help that a jQuery plugin is expecing a global instance of `$` since it's being `import`ed into the plugin library.  For that, something like the [`ProvidePlugin`](https://webpack.js.org/plugins/provide-plugin/) for **webpack** comes in handy.

Hope that helps!
