### ISSUE TITLE
webpack / hooks issue

### ISSUE THREAD

**Issue by unparagoned** [developit/karmatic#23]
I'm a bit new to js so I may be making a silly mistake. I'm doing the following
```
mkdir test
cd test
npm init -y
npm i -D karmatic
```
Then I edit package.json
```
{
    "scripts": {
    	"test": "karmatic"
    }
}
```
But when I run npm test I get an error. It cannot find module 'webpack'. I tried install webpack but then I get an error about Tapable.plugin is depreciated. Use new API on hooks instead.

Are there any alternatives to getting jasmine, karma and chrome working?

**Comment by developit** [comment]
Hi there!  You almost had it working - the error message is really confusing, it actually just couldn't find your JavaScript files (because there aren't any).

If you create file `index.js` and put something in it, it'll work fine, though you'll want to add tests. The resulting directory structure should look like:

```
package.json
index.js
index_test.js
```

Here's a gist with a working example:
https://gist.github.com/developit/acd8a075350eeb6574439e92888c50cf
